const CATEGORY_LABELS = {
  all: { ko: "전체", en: "All" },
  life: { ko: "인생", en: "Life" },
  courage: { ko: "용기", en: "Courage" },
  growth: { ko: "성장", en: "Growth" },
  relationship: { ko: "관계", en: "Connection" },
};

const CATEGORIES = ["all", "life", "courage", "growth", "relationship"];

const I18N = {
  ko: {
    appSettings: "앱 설정",
    splashSub: "오늘의 명언을 준비하고 있어요",
    subtitle: "디즈니 명언 카드",
    navHome: "홈",
    navSaved: "보관함",
    collectionTitle: "저장한 명언",
    emptySaved: "아직 저장한 명언이 없어요.<br />마음에 드는 카드의 하트를 눌러보세요.",
    prevQuote: "이전 명언",
    nextQuote: "다음 명언",
    like: "좋아요",
    copy: "텍스트 복사",
    download: "이미지로 저장",
    switchLanguage: "영어로 변경",
    themeLight: "라이트 테마로 변경",
    themeDark: "다크 테마로 변경",
    saved: "보관함에 저장했어요",
    removed: "보관함에서 제거했어요",
    copied: "텍스트를 복사했어요",
    copyFailed: "복사를 지원하지 않는 브라우저예요",
    downloading: "이미지를 만들고 있어요",
    downloadDone: "이미지를 저장했어요",
    downloadFailed: "이미지 저장에 실패했어요. 다시 시도해 주세요.",
    themeChangedLight: "라이트 테마로 전환했어요",
    themeChangedDark: "다크 테마로 전환했어요",
    languageChanged: "한국어로 전환했어요",
  },
  en: {
    appSettings: "App settings",
    splashSub: "Preparing today's quote",
    subtitle: "Disney quote cards",
    navHome: "Home",
    navSaved: "Saved",
    collectionTitle: "Saved Quotes",
    emptySaved: "No saved quotes yet.<br />Tap the heart on a card you love.",
    prevQuote: "Previous quote",
    nextQuote: "Next quote",
    like: "Like",
    copy: "Copy text",
    download: "Save as image",
    switchLanguage: "Switch to Korean",
    themeLight: "Switch to light theme",
    themeDark: "Switch to dark theme",
    saved: "Saved to your collection",
    removed: "Removed from your collection",
    copied: "Copied to clipboard",
    copyFailed: "Clipboard copy is not available",
    downloading: "Creating image",
    downloadDone: "Image saved",
    downloadFailed: "Could not save the image. Please try again.",
    themeChangedLight: "Switched to light theme",
    themeChangedDark: "Switched to dark theme",
    languageChanged: "Switched to English",
  },
};

const QUOTES = [
  {
    id: "lionking-01",
    quoteEn: "Remember who you are.",
    quoteKo: "네가 누구인지 기억해.",
    sourceKo: "라이온 킹",
    sourceEn: "The Lion King",
    year: 1994,
    keywordsKo: ["자아", "정체성"],
    keywordsEn: ["self", "identity"],
    category: "life",
  },
  {
    id: "lionking-02",
    quoteEn: "The past can hurt. But you can either run from it or learn from it.",
    quoteKo: "과거는 아플 수 있어. 하지만 도망칠 수도, 배울 수도 있지.",
    sourceKo: "라이온 킹",
    sourceEn: "The Lion King",
    year: 1994,
    keywordsKo: ["성장", "극복"],
    keywordsEn: ["growth", "overcome"],
    category: "growth",
  },
  {
    id: "tangled-01",
    quoteEn: "Venture outside your comfort zone. The rewards are worth it.",
    quoteKo: "안전지대를 벗어나 봐. 그만한 가치가 있어.",
    sourceKo: "라푼젤",
    sourceEn: "Tangled",
    year: 2010,
    keywordsKo: ["도전", "모험"],
    keywordsEn: ["challenge", "adventure"],
    category: "courage",
  },
  {
    id: "frozen-01",
    quoteEn: "Fear will be your enemy.",
    quoteKo: "두려움이야말로 너의 적이 될 거야.",
    sourceKo: "겨울왕국",
    sourceEn: "Frozen",
    year: 2013,
    keywordsKo: ["용기", "두려움"],
    keywordsEn: ["courage", "fear"],
    category: "courage",
  },
  {
    id: "frozen2-01",
    quoteEn: "Do the next right thing.",
    quoteKo: "지금 할 수 있는 다음 옳은 일을 해.",
    sourceKo: "겨울왕국 2",
    sourceEn: "Frozen II",
    year: 2019,
    keywordsKo: ["한 걸음", "선택"],
    keywordsEn: ["next step", "choice"],
    category: "life",
  },
  {
    id: "moana-01",
    quoteEn: "The call isn't out there at all. It's inside me.",
    quoteKo: "그 부름은 멀리 있는 게 아니야. 내 안에 있어.",
    sourceKo: "모아나",
    sourceEn: "Moana",
    year: 2016,
    keywordsKo: ["자아 발견", "내면"],
    keywordsEn: ["self-discovery", "inner voice"],
    category: "life",
  },
  {
    id: "moana-02",
    quoteEn: "Sometimes our strengths lie beneath the surface.",
    quoteKo: "우리의 강점은 때로 겉으로 보이지 않는 곳에 있어.",
    sourceKo: "모아나",
    sourceEn: "Moana",
    year: 2016,
    keywordsKo: ["잠재력", "믿음"],
    keywordsEn: ["potential", "faith"],
    category: "growth",
  },
  {
    id: "mulan-01",
    quoteEn: "The flower that blooms in adversity is the most rare and beautiful of all.",
    quoteKo: "역경 속에서 피는 꽃이 가장 귀하고 아름다워.",
    sourceKo: "뮬란",
    sourceEn: "Mulan",
    year: 1998,
    keywordsKo: ["역경", "회복"],
    keywordsEn: ["adversity", "resilience"],
    category: "growth",
  },
  {
    id: "pocahontas-01",
    quoteEn: "Listen with your heart.",
    quoteKo: "마음으로 들어 봐.",
    sourceKo: "포카혼타스",
    sourceEn: "Pocahontas",
    year: 1995,
    keywordsKo: ["공감", "마음"],
    keywordsEn: ["empathy", "heart"],
    category: "relationship",
  },
  {
    id: "cinderella-01",
    quoteEn: "Have courage and be kind.",
    quoteKo: "용기를 갖고 친절하게 살아.",
    sourceKo: "신데렐라",
    sourceEn: "Cinderella",
    year: 2015,
    keywordsKo: ["친절", "용기"],
    keywordsEn: ["kindness", "courage"],
    category: "relationship",
  },
  {
    id: "peterpan-01",
    quoteEn: "All it takes is faith and trust.",
    quoteKo: "필요한 건 믿음과 신뢰뿐이야.",
    sourceKo: "피터 팬",
    sourceEn: "Peter Pan",
    year: 1953,
    keywordsKo: ["믿음", "신뢰"],
    keywordsEn: ["faith", "trust"],
    category: "relationship",
  },
  {
    id: "pooh-01",
    quoteEn: "You're braver than you believe, stronger than you seem, and smarter than you think.",
    quoteKo: "넌 네가 믿는 것보다 용감하고, 보이는 것보다 강하며, 생각보다 똑똑해.",
    sourceKo: "곰돌이 푸",
    sourceEn: "Winnie the Pooh",
    year: 1997,
    keywordsKo: ["자신감", "격려"],
    keywordsEn: ["confidence", "encouragement"],
    category: "courage",
  },
  {
    id: "pooh-02",
    quoteEn: "Sometimes the smallest things take up the most room in your heart.",
    quoteKo: "가장 작은 것들이 때로 마음속 가장 큰 자리를 차지해.",
    sourceKo: "곰돌이 푸",
    sourceEn: "Winnie the Pooh",
    year: 2011,
    keywordsKo: ["사랑", "소중함"],
    keywordsEn: ["love", "precious"],
    category: "relationship",
  },
  {
    id: "walle-01",
    quoteEn: "I don't want to survive. I want to live.",
    quoteKo: "난 그저 살아남고 싶은 게 아니야. 제대로 살고 싶어.",
    sourceKo: "월-E",
    sourceEn: "WALL-E",
    year: 2008,
    keywordsKo: ["삶", "의미"],
    keywordsEn: ["life", "meaning"],
    category: "life",
  },
  {
    id: "up-01",
    quoteEn: "Adventure is out there!",
    quoteKo: "모험은 바로 저 밖에 있어!",
    sourceKo: "업",
    sourceEn: "Up",
    year: 2009,
    keywordsKo: ["모험", "시작"],
    keywordsEn: ["adventure", "beginning"],
    category: "courage",
  },
  {
    id: "toystory-01",
    quoteEn: "To infinity and beyond!",
    quoteKo: "무한한 공간, 저 너머로!",
    sourceKo: "토이 스토리",
    sourceEn: "Toy Story",
    year: 1995,
    keywordsKo: ["꿈", "도전"],
    keywordsEn: ["dream", "challenge"],
    category: "courage",
  },
  {
    id: "findingnemo-01",
    quoteEn: "Just keep swimming.",
    quoteKo: "계속 헤엄쳐.",
    sourceKo: "니모를 찾아서",
    sourceEn: "Finding Nemo",
    year: 2003,
    keywordsKo: ["끈기", "계속"],
    keywordsEn: ["persistence", "keep going"],
    category: "growth",
  },
  {
    id: "coco-01",
    quoteEn: "Our memories have to be passed down by those who knew us in life.",
    quoteKo: "기억은 우리를 아는 사람들에 의해 이어져.",
    sourceKo: "코코",
    sourceEn: "Coco",
    year: 2017,
    keywordsKo: ["가족", "기억"],
    keywordsEn: ["family", "memory"],
    category: "relationship",
  },
  {
    id: "soul-01",
    quoteEn: "Life is full of possibilities. You just need to know where to look.",
    quoteKo: "삶은 가능성으로 가득해. 어디를 봐야 하는지만 알면 돼.",
    sourceKo: "소울",
    sourceEn: "Soul",
    year: 2020,
    keywordsKo: ["가능성", "시선"],
    keywordsEn: ["possibility", "perspective"],
    category: "life",
  },
  {
    id: "insideout-01",
    quoteEn: "Crying helps me slow down and obsess over the weight of life's problems.",
    quoteKo: "울음은 내가 잠시 멈춰 삶의 무게를 받아들이게 해 줘.",
    sourceKo: "인사이드 아웃",
    sourceEn: "Inside Out",
    year: 2015,
    keywordsKo: ["감정", "치유"],
    keywordsEn: ["emotion", "healing"],
    category: "life",
  },
];
